config/routes.rb
Rails.application.routes.draw do
 
 
  devise_for :users

  root to: "homes#top"
  get "home/about"=>"homes#about"
  
  resources :users, only:[:index, :show, :edit, :update]
  
  resources :books, only:[:index, :show, :edit, :create, :destroy, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!,except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?


  private


  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def create
  end

  def destroy
  end

  def update
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
 <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="container">
    <a class="navbar-brand" href="/"><span>Bookers</span></a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
       <li>
        <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
        <i class="fas fa-home"></i>Home
        <% end %>
       </li>
       <li>
        <%= link_to users_path,class: 'nav-link text-light' do %>
        <i class="fa-solid fa-users"></i>Users
        <% end %>
       </li>
       <li>
        <%= link_to books_path, class: 'nav-link text-light' do %>
        <i class="fa-solid fa-book-open"></i>Books
        <% end %>
       </li>
       <li>
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
        <i class="fa-solid fa-right-from-bracket"></i>log out
        <% end %>
        </li>
        <% else %>
        <li>
         <%= link_to root_path, class: 'nav-link text-light' do %>
         <i class="fas fa-home"></i>Home
         <% end %>
        </li>
        <li>
         <%= link_to home_about_path, class: 'nav-link text-light' do %>
         <i class="fas fa-link"></i>About
         <% end %>
        </li>
        <li>
         <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
         <i class="fas fa-user-plus"></i> signup
         <% end %>
        </li>
        <li>
         <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
         <i class="fas fa-sign-in-alt"></i> login
         <% end %>
        </li>
         <% end %>
       </ul>
      </div>
   </div>
  </nav>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
     <title>Bookers2</title>
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width,initial-scale=1">
     <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>